language: android
android:
  components:
    - build-tools-19.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-16
    - sysimg-16
    - sys-img-armeabi-v7a-android-18
  licences:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

before_install: 
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "mvn --version"
  - "cd third-party/"
  - "./mvnInstall.sh"
  - "cd ../"

script:
  - mvn clean install
  - ./runEnd2EndTests.sh


env:
  global:
    - secure: "qOCTIN+N9lYVx/rp7Qu5xcyaFPLsf64UYSOY5dq+4jOx5vokQfb0vwFxKyDJcUD7ow3GMhw11280HE2OZ3Xk+1xRGWND5Axhey8BPOjqT9D+vjKY2o2Q2ZmUbBTapL/lDixjnV9Gk/bJLytPLNaaA7S/HNfp0g03bWhLanz5fgg="
    - secure: "BzwsXUidLx7X733KzZDwvuXsIiFD0WazDABk8FM3BuvkJnGd8xp84A0ZwZ76PYvrxWp/MncyaOytkrnNA86rnBmpWvcnWzEuBVoDY/cEc4q1SnLjgsRByanNBPoYopFHAVRI2zvkU8hSBVFZC2+ABi3vpNhgYr0LtBhZouBTX5E="
